working_directory = "/Users/nielsdobbelaar/Documents" 

[window]
decorations = "None"
padding = { x = 2, y = 10 }
startup_mode = "Maximized"
title = "Battlestation"
# option_as_alt = "OnlyLeft"

[font]
size = 15

[cursor]
style = { shape = "Beam", blinking = "Off"}

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.cursor]
text = "#b493a9"  # Default
cursor = "CellForeground"  # Default
